# Generated by Django 4.1.7 on 2023-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_description', models.CharField(max_length=100)),
                ('category_descr', models.CharField(max_length=20)),
                ('expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
    ]
