# Generated by Django 4.1.7 on 2023-03-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category_descr',
            field=models.CharField(choices=[('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('PERSONAL CARE', 'Personal Care'), ('FOOD_&_DINING', 'Food & Dining'), ('CLOTHING', 'Clothing'), ('GIFTS_DONATIONS', 'Gifts & Donations'), ('UTILITIES', 'Utilities'), ('TRANSPORT', 'Transport'), ('INVESTMENTS', 'Investments'), ('SAVINGS', 'Savings'), ('TRAVEL', 'Travel'), ('FEES_CHARGES', 'Fees & Charges'), ('TAXES', 'Taxes'), ('HOUSING', 'Housing'), ('HEALTHCARE', 'Healthcare'), ('MISCHELLANEOUS', 'Miscellaneous')], max_length=50),
        ),
    ]
